name: Youtube-Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies & build
        run: |
          npm install
          # Disable CI flag so warnings don't break the build
          CI=false npm run build

      - name: Deploy build folder to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.NEW_PAGES_SSH_HOST }}
          username: ${{ secrets.NEW_PAGES_SSH_USERNAME }}
          key: ${{ secrets.NEW_PAGES_SSH_PRIVATE_KEY }}
          port: 22
          source: "build/*"
          target: "/var/www/html/youtube-demo"
